#!/usr/bin/php
<?php
    
    // requirements
    // require("helpers.php");

    // CS50 Library
    require("../vendor/library50-php-5/CS50/CS50.php");
    CS50::init(__DIR__ . "/../config.json");
    
    
    if($argc != 2)
    {
        return false;
    }
    
    elseif(!file_exists($argv[1]))
    {
        echo("File does not exists.");
        return false;
    }
    
    elseif(!is_readable($argv[1]))
    {
        echo("File is not readable.");
        return false;
    }
    else
    {
        if (($handle = fopen("US.txt", "r")) !== FALSE)
        {
            while (($mydata = fgetcsv($handle, 1000, "\t")) !== FALSE)
            {
                $mydata = fgetcsv($handle, 1000, "\t");
                
                CS50::query("INSERT INTO places (country_code, postal_code, place_name, admin_name1, admin_code1, admin_name2, admin_code2, admin_name3, admin_code3, latitude, longitude, accuracy) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)", $mydata[0] , $mydata[1], $mydata[2], $mydata[3], $mydata[4], $mydata[5], $mydata[6], $mydata[7], $mydata[8], $mydata[9], $mydata[10], $mydata[11]);                                                                
            }
        fclose($handle);
        
        }
    }
?>